### PR TITLE
Support CM3D2 1.49+, general clean-up

### PR DESCRIPTION
**Pull request by denikson**
Hey!

Nice work on this plug in: makes a whole lot easier to play CM3D2 without the need of Sybaris + ReiPatcher combination.

However, it seems CM3D2 was updated some time ago, which broke some functionality: for instance, ImportCM.LoadTexture now doesn't return `byte[]`, which caused some invalid IL getting generated.
So I went ahead and fixed that.

Moreover, I noticed that most of the code is taken straight from decompiled Unified Translation Plugin and Maid Fiddler (you could've used the open source code instead of decompiling it). 
I cleaned up most of the decompiled code by hand.

I tested this version with CM3D2 1.51, and it seemed to work fine.

Please test these edits out, and possibly merge them.

### CODE REVIEW

**Comment by denikson** [comment]
One important mention: due to how some method signatures were changed in CM3D2, these edits are not compatible with previous versions of CM3D2 (I'd guess versions 1.40 or older).

**Comment by liquidmack** [comment]
I built plugin with your edits.
I have sybaris with 1.52 patch. System text translation 07/13/17. UI Translation v. 4.2

For some reason maid stats are not being translated correctly.  
ytg_maid_skill_stats.txt to be precise.

[ytg_maid_skill_stats.txt](https://github.com/zklm/CM3D2.TranslationPlus/files/1185967/ytg_maid_skill_stats.txt)


transproblem

**Comment by denikson** [comment]
Thank you for the info, @liquidmack !
Silly me: I forgot to unescape `\` character if the next character wasn't a special one. That broke some RegExes, which in turn prevented some labels from being translated properly.

It should work fine now.

**Comment by denikson** [comment]
As a separate note: it seems that some file still contains some malformed encoding, which prevents Linguist from properly identifying source code and creating proper diffs. 

I'll try to find the file, but currently it's not that big a concern.

**Comment by liquidmack** [comment]
Awesome, Thanks for doing all this, you're a hero we need, but don't deserve.

My biggest battle right now is to make it work with VNR.
When VNR is active before cm3d2, it causes game to crash after second screen. Launching VNR and using game wizard to hook it with cm3d2 works, using ITH, but there is no one correct dialogue text thread. Most of them are flooded with other strings. One text thread can work with one scene, but becomes gibberish with other. Sometimes they go into crazy infinite repetition making VNR spam same translation over whole gamescreen.


[Crash VNR 07322017.zip](https://github.com/zklm/CM3D2.TranslationPlus/files/1186015/Crash.VNR.07322017.zip)


There is none sybaris only dialogue-to-clipboard plugin (I know about reipatcher and sybaris combo)
Translation Aggregator doesn't work.

safs

PS:
Stats translation works fine now, Thanks!
sdjjfjs

**Comment by QuelLikaPig** [comment]
Mind you the texture loader got broken at V1.49 when VR component of the game, which is used to be a separate plugin merged with the game.

it works just fine on V1.48 and older.

Also, there are other things that might need to be addressed here:

1. TranslationPlus seems not working with most buttons and texts in Vacation mode
2. the "...?" somehow interfere with text that has "......?" causing that text to not be translated properly despite getting the correct translation. I had to resort to edit the original script to get that working.
3. It would be better if similar text in two different scripts to load their respective translation separately, not both of them getting the same text because, despite the same text, it might mean differently if the context for each text is different.

**Comment by denikson** [comment]
@liquidmack Glad it works now.

A short comment unrelated to this PR:
Yes, you can't really use machine translation programs properly with CM3D2 without the text-to-clipboard plug-in. There are a few options, however:

1. Rewrite the plug-in's patcher to use Sybaris. That is not really hard, since the main patching code would be the same, but some method names would be different. However, an update to the ReiPatcher plug-in would require an update to the respective Sybaris version.
2. One could write a "patcher" patcher, that would allow to use ReiPatcher patchers with Sybaris. However, not all patchers would work (because of the way Sybaris works; I won't go into details), and it would require quite a lot of "polyfills" and "hacks".
3. There is another alternative to ReiPatcher: [UULaucher](http://umaiumeunion.github.io/tools/uulauncher/) (*shameless self-promotion*). Currently it uses ReiPatcher executable to patch assemblies, but it works like Sybaris in a sense that it's one-click-does-all and that it patches assemblies only before the game is launched and restores them after the game is closed (or when UULauncher is used again). However, it's still quite weakly documented (since it wasn't my first priority) and first-time setup is a bit wonky at the moment.

Anyway, back to the main topic.

@QuelLikaPig Thank you for the info! I only had Assembly-CSharp.dll from 1.43 and 1.50, so I assumed the change happened somewhere between there. 
I updated the title accordingly.

As for those additional issues, do they persist on the unedited version of TranslationPlus and ReiPatcher's Unified Translation Plugin (or did I manage to break some functionality again)?

Here's a brief response to your points:

1. Currently I don't have the necessary DLC to enable Vacation mode (at least I don't see the mode in CM3D2), but since the code is in Assembly-CSharp.dll (which is shipped with version updates, not DLC), I'll look into it. Might be either that the textures require some special naming or that CM3D2 uses some different method to obtain the texture.
2. Could you provide an example? This might be solved on the translation side, but we'll see.
3. You can do that, provided that the same dialog occurs in two different scene levels. However, if the exact same strings are on the same levels (for instance, same VIP event), there really any way to uniquely identify which translation to use. Unless the Unity's labels provide some kind of consistent, unambiguous way to identify every single one text piece to translate, it's not really easily doable. You could make some kind of counter, for instance, but I bet a proper implementation would require more work than what it's worth. *Nonetheless*, I'll try to look into that one too.

**Comment by QuelLikaPig** [comment]
It's more like this

`おーい[HF]……？`

when not translated it becomes like this in the message window:

`おーい[HF]...?`

as you can see, the "......?" part got translated somehow

so if I want to translate that with this:

`おーい[HF]……？	Hey [HF] ...?`

it will stil show me this:

`おーい[HF]...?`

somehow the "...?" prevent that from getting translated. Mind you the distance between [HF] token and "...?" doesn't really matter in this case like this one:

`俺の気持ち……ちゃんと[HF]に伝わった……？`

as it still show this one

`俺の気持ち……ちゃんと[HF]に伝わった...?`

instead of "Did you... receive my feeling properly...?"

**Comment by denikson** [comment]
@QuelLikaPig I see now.

Here's the problem: TranslationPlus (and Unified Translation Plugin) convert translation with tags like [HF] to RegExes which are then used to match the original text to translation. Not only does this cause some kind of RegEx matching problems (which in turn cause the issue you're mentioning), but in order to find the right translation, the plugin iterates over **every single loaded RegEx on the level** to find a match.

Is this bad? No, unless there are a lot of them. In any case, pure iteration is almost always slower than using a dictionary to store constant string translation.

There is a quick solution, but it requires hooking additional methods, and it's a bit hacky at the moment (so don't expect the functionality to preserve over updates).
Therefore I'm not adding it to the current PR. Instead, you can find it on the [indev branch](https://github.com/denikson/CM3D2.TranslationPlus/tree/indev) of my fork.
I tested it in the VIP event your examples came from, and it worked quite well. Moreover, it should be a tad faster, and text speed settings other than "instant" should actually work now, too.

I may look into some better ways to handle translations altogether, but I'll probably push the changes to the indev branch until this PR is accepted.

If you have any more suggestions other than apparent problems with this PR, I suggest creating an issue to my fork, so as not to clutter this PR.

**Comment by QuelLikaPig** [comment]
Thanks. I'll take a look at that later. 

Honestly there are quite a number of issue with UTL for the pass 2 years and the original author doesn't seen to take much effort on it.

**Comment by denikson** [comment]
Again, thank you all for reporting all the issues.

As it seems, the author isn't really active -- I bet pigs will fly before this PR is reacted to.

Therefore I went ahead and wrote the whole plug-in from scratch. The only thing that remain are the method names to preserve the public API and the general functionality (string, texture and asset translation is done using the same technique).

You can find the project here: [YATranslator](https://github.com/denikson/CM3D2.YATranslator).

If you have any more suggestions or problems, report them there.

I'm closing this PR and removing my fork in the near future to favour the new translation plug-in.

**Pull request closed without merging**
